CREATE TABLE EARTHQUAKES (
    ID RAW(16) NOT NULL, SOURCE VARCHAR2(50 CHAR) NOT NULL, EXTERNAL_ID VARCHAR2(200 CHAR) NOT NULL,
    ORIGIN_TIME TIMESTAMP WITH TIME ZONE NOT NULL, LATITUDE NUMBER(9,6) NOT NULL,
    LONGITUDE NUMBER(9,6) NOT NULL, DEPTH_KM NUMBER(10,3), MAGNITUDE NUMBER(5,2),
    MAGNITUDE_TYPE VARCHAR2(30 CHAR), PLACE VARCHAR2(500 CHAR), EVENT_URL VARCHAR2(1000 CHAR),
    PROVIDER_UPDATED_AT TIMESTAMP WITH TIME ZONE, PROVIDER_STATUS VARCHAR2(30 CHAR),
    TSUNAMI NUMBER(1), ALERT_LEVEL VARCHAR2(20 CHAR), SIGNIFICANCE NUMBER, RAW_PAYLOAD CLOB,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL, UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_EARTHQUAKES PRIMARY KEY (ID),
    CONSTRAINT UQ_EARTHQUAKES_SOURCE_EXTERNAL UNIQUE (SOURCE, EXTERNAL_ID),
    CONSTRAINT CK_EARTHQUAKES_LATITUDE CHECK (LATITUDE BETWEEN -90 AND 90),
    CONSTRAINT CK_EARTHQUAKES_LONGITUDE CHECK (LONGITUDE BETWEEN -180 AND 180),
    CONSTRAINT CK_EARTHQUAKES_TSUNAMI CHECK (TSUNAMI IN (0, 1)),
    CONSTRAINT CK_EARTHQUAKES_RAW_JSON CHECK (RAW_PAYLOAD IS JSON)
);
CREATE INDEX IX_EARTHQUAKES_ORIGIN_TIME ON EARTHQUAKES (ORIGIN_TIME);
CREATE INDEX IX_EARTHQUAKES_MAGNITUDE ON EARTHQUAKES (MAGNITUDE);
CREATE INDEX IX_EARTHQUAKES_COORDINATES ON EARTHQUAKES (LATITUDE, LONGITUDE);
