ALTER TABLE EARTHQUAKES ADD (
    PROVIDER_UPDATED_AT TIMESTAMP WITH TIME ZONE,
    PROVIDER_STATUS VARCHAR2(30 CHAR),
    TSUNAMI NUMBER(1),
    ALERT_LEVEL VARCHAR2(20 CHAR),
    SIGNIFICANCE NUMBER,
    RAW_PAYLOAD CLOB
);

ALTER TABLE EARTHQUAKES ADD CONSTRAINT CK_EARTHQUAKES_TSUNAMI
    CHECK (TSUNAMI IN (0, 1));

ALTER TABLE EARTHQUAKES ADD CONSTRAINT CK_EARTHQUAKES_RAW_JSON
    CHECK (RAW_PAYLOAD IS JSON);
